openapi: 3.0.0

info:
  description: API para manipulação de CTe-e
  version: "1.0.0"
  title: Inventti EDocs CTePack
  contact:
    email: contato@inventti.com.br

security:
  - {}
  - ApiKeyAuth: [] 

paths:

  /api/CTe/Recepcionar:
    post:
      summary: Execução de comandos sobre CT-es
      operationId: recepcionarComandoAssincrono
      description: Faz a execução de um comando
      requestBody:
        content:
          application/xml:
            schema:
              type: string

      responses:
        '200':
          description: Resposta do registro para processamento
          content:
            application/xml:
              schema:
                type: string
        '500':
          description: Falha não tratada no servidor
          
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: token
