openapi: 3.0.0

info:
  description: API para emissão de NF-e e NFC-e
  version: "1.0.0"
  title: Inventti EDocs NFePack
  contact:
    email: contato@inventti.com.br

security:
  - {}
  - ApiKeyAuth: [] 

paths:
  /api/nfe/RecepcionarNotaAssincrona:
    post:
      summary: Emissão de nota fiscal
      operationId: recepcionarNotaAssincrona
      description: Faz a emisão de um XML de NF-e ou NFC-e
      requestBody:
        content:
          application/xml:
            schema:
              type: string

      responses:
        '200':
          description: Resposta do registro para processamento assíncrono do XML fiscal
          content:
            application/xml:
              schema:
                type: string

        '500':
          description: Falha não tratada no servidor

  /api/nfe/RecepcionarComandoAssincrono:
    post:
      summary: Execução de comandos sobre notas fiscais
      operationId: recepcionarComandoAssincrono
      description: Faz a execução de um comando sobre um XML fiscal
      requestBody:
        content:
          application/xml:
            schema:
              type: string

      responses:
        '200':
          description: Resposta do registro para processamento
          content:
            application/xml:
              schema:
                type: string

        '500':
          description: Falha não tratada no servidor

  /api/NFe/RecepcionarEventoFiscalAssincrono:
    post:
      summary: Recepção de eventos fiscais
      operationId: recepcionarEventoFiscalAssincrono
      description: Faz o registro de evento fiscal de forma assíncrona
      requestBody:
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: Resposta do registro para processamento
          content:
            application/xml:
              schema:
                type: string

        '500':
          description: Falha não tratada no servidor
        
  /api/NFe/RecepcionarInutilizacaoAssincrona:
    post:
      summary: Recepção de inutilizações
      operationId: recepcionarInutilizacaoAssincrona
      description: Faz o registro de inutilização de forma assíncrona
      requestBody:
        content:
          application/xml:
              schema:
                type: string
      responses:
        '200':
          description: Resposta do registro para processamento
          content:
            application/xml:
              schema:
                type: string
                example: ''

        '500':
          description: Falha não tratada no servidor
          
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: token
